apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneudacity
  labels:
    app: capstoneudacity
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstoneudacity
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstoneudacity
    spec:
      containers:
      - image: shijujohn1093/capstoneudacity:@BuildNumber@
        imagePullPolicy: Always
        name: capstoneudacity
        ports:
        - containerPort: 80
          protocol: TCP